### ISSUE TITLE
Use of this tool for Archivematica project?

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/upholstery#18]
We created this project as a front-end to CouchDB.

As an additional layer of security, I'd like us to consider using this, or something like it, as a proxy front-end to Archivematica.

While Archivematica has its own password system, ensuring that the only people who can type a password are those people who have already authenticated with us would be ideal.

It is possible that there will be a plug-in we can create for Archivematica to authenticate against our platform authentication system.

Looking for thoughts from @SaschaAdler and @hstgelais-crkn-rcdr

**Comment by SaschaAdler** [comment]
It looks like Archivematica [now supports OpenID Connect, with specific support for Azure Active Directory stuff](https://github.com/artefactual/archivematica/blob/stable/1.12.x/src/dashboard/install/README.md#oidc-variables), which means that we might be able to authenticate into Archivematica interfaces with our @crkn.ca IDs.

I have access to the CRKN Azure config dashboard, but we might want to get Hugo access to it as well.

This would mean we wouldn't need to use our own authorization layer.

**Comment by RussellMcOrmond** [comment]
This is great to hear.  Created a ticket for Hugo to investigate in more detail, and make appropriate recommendations.
