### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/upholstery#6]
We're adopting HAProxy for the entire access platform, and so upholstery will need to work behind it.

**Comment by SaschaAdler** [comment]
See https://github.com/crkn-rcdr/upholstery/commit/47ea5515eb5a1e2418a0dc3f180bd02f3ac6db9a and the new image I've pushed.

Russell can close this when we've confirmed it works in production.

**Comment by RussellMcOrmond** [comment]
I'm not sure what tag you used to push...

```
root@mamirolle:~# docker pull docker.c7a.ca/upholstery:20200214
Error response from daemon: manifest for docker.c7a.ca/upholstery:20200214 not found: manifest unknown: manifest unknown
root@mamirolle:~# docker pull docker.c7a.ca/upholstery:20200215
Error response from daemon: manifest for docker.c7a.ca/upholstery:20200215 not found: manifest unknown: manifest unknown
root@mamirolle:~# docker pull docker.c7a.ca/upholstery:20200212
Error response from daemon: manifest for docker.c7a.ca/upholstery:20200212 not found: manifest unknown: manifest unknown
root@mamirolle:~# 

```

I built and pushed docker.c7a.ca/upholstery:20200214

**Comment by SaschaAdler** [comment]
Did 20200213 not work?

Sascha Adler
Lead Application Developer, CRKN

________________________________

**Comment by RussellMcOrmond** [comment]
OK.  Odd.  Seems that even in what I cut-and-pasted I clearly didn't check for the right tag.  Sorry for that confusion.

I've tested on Mamirolle, so can close this ticket.   Will roll out on other production servers and point DNS to one (or more) of them.

BTW: Simplifying the apps by putting the https check in HAproxy is a much better idea than what I was thinking.
