### ISSUE TITLE
Replacing current usage of Upholstery for D10n.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/upholstery#8]
https://github.com/crkn-rcdr/d10n is currently offered from via Apache wrapped with upholstery in order to check the JWT.

As upholstery can become much more useful as an API provider for clients #2 , we will want to set up something different for d10n.

**Comment by RussellMcOrmond** [comment]
We can choose one of the ideas discussed, or think of something different:

* Set up /demo/ or similar proxy with Upholstery that would point to a different URL than CouchDB (keep current Apache)
* Copy the current simple functionality of Upholstery to the d10n project as a replacement for Apache that checks the JWT
* Create a 'deploy2couch' tool that would copy the d10n directory of files to become attachments to a CouchDB document (Test at: https://upholstery.canadiana.ca/d10n/demo/wipProcessStatus.html ).  Would be used in conjunction with Kivik for local testing before deploying to production databases.
  * Tool could be written in Perl
  * Tool could be an update to https://github.com/crkn-rcdr/kivik that supports attachments.

**Comment by SaschaAdler** [comment]
Your first option seems the easiest to set up, and what I'm inclined to do quickly.

**Comment by RussellMcOrmond** [comment]
To keep the development environments as similar to production as possible, I suggest rather than a proxy that we use something such as:

* https://github.com/cloudhead/node-static , which was inspired from
  * https://github.com/mhansen/antinode
  * https://github.com/tomvit/node-paperboy

This way upholstery itself can be used during maintenance of these scripts, rather than a separate Apache configuration.

Unless there is opposition to this option, I'll volunteer to take this on.

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/upholstery/pull/11 and https://github.com/crkn-rcdr/d10n/pull/10 have the changes required to serve the d10n demo files as static files from Upholstery.

It is currently configured to use https://github.com/crkn-rcdr/d10n as a subproject.  That repository is private, and because it historically contained passwords we may want to keep it that way.  This repository is public.  That mixture may not be desirable:

* We can copy the /demo/ files from d10n to /demo/ within this repository, and copy that into the contaoner.
* We can change whatever passwords were previously in the d10n repository (if any), and make that repository public.

**Comment by RussellMcOrmond** [comment]
When discussing having a private subproject, it was decided to not worry about it as it was unlikely anyone else was cloning this project.  If this changes, we can adjust accordingly.
